/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Panels;

import JISS.Judge;
import JISS.Lawyer;
import JISS.Registrar;
import JISS.User;
import java.awt.CardLayout;
import JISS.Main;
import JISS.Case;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Sandesh
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    
    private Main rapplet ;
    
    private static Registrar _registrar ;
    private static Lawyer _lawyer ;
    private static Judge _judge ;
    
    private static int _cut ;
    
    public static User getCU() throws Exception{
        if(_cut==User.JUDGE) return _judge;
        else if(_cut==User.LAWYER) return _lawyer;
        else if(_cut==User.REGISTRAR) return _registrar;
        throw new Exception("Accessing current user without initialization");
    }
    
    public static int getCUT(){
        return _cut ;
    }
    
    public LoginPanel() {
        initComponents();
        _registrar = null ;
        _lawyer = null ;
        _judge = null ;
        b_history.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_mview = new javax.swing.JPanel();
        p_blank = new javax.swing.JPanel();
        p_sview = new javax.swing.JPanel();
        p_loginPane = new javax.swing.JPanel();
        i_loginid = new javax.swing.JTextField();
        i_pswd = new javax.swing.JPasswordField();
        b_login = new javax.swing.JButton();
        l_login_result = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p_sidePane = new javax.swing.JPanel();
        b_logout = new javax.swing.JButton();
        b_search = new javax.swing.JButton();
        b_history = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_acc_det = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new Color(51,153,255,50));
        setName(""); // NOI18N

        p_mview.setBackground(new Color(255,255,255,0));
        p_mview.setLayout(new java.awt.CardLayout());

        p_blank.setBackground(new Color(255,255,255,100));

        javax.swing.GroupLayout p_blankLayout = new javax.swing.GroupLayout(p_blank);
        p_blank.setLayout(p_blankLayout);
        p_blankLayout.setHorizontalGroup(
            p_blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        p_blankLayout.setVerticalGroup(
            p_blankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        p_mview.add(p_blank, "card2");

        p_sview.setBackground(new Color(255,255,255,100));
        p_sview.setOpaque(false);
        p_sview.setLayout(new java.awt.CardLayout());

        p_loginPane.setBackground(new Color(255,255,255,100));

        i_pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_pswdActionPerformed(evt);
            }
        });

        b_login.setText("Login");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        l_login_result.setBackground(new Color(255,255,255,0));
        l_login_result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_login_result.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JISS");

        javax.swing.GroupLayout p_loginPaneLayout = new javax.swing.GroupLayout(p_loginPane);
        p_loginPane.setLayout(p_loginPaneLayout);
        p_loginPaneLayout.setHorizontalGroup(
            p_loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_loginPaneLayout.createSequentialGroup()
                .addGroup(p_loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_loginPaneLayout.createSequentialGroup()
                        .addGroup(p_loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_loginPaneLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_loginPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p_loginPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p_loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_loginid)
                            .addGroup(p_loginPaneLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(l_login_result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(i_pswd))))
                .addContainerGap())
        );
        p_loginPaneLayout.setVerticalGroup(
            p_loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_loginPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(i_loginid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(i_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_login_result, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        p_sview.add(p_loginPane, "card2");

        p_sidePane.setBackground(new Color(255,255,255,100));
        p_sidePane.setToolTipText("SidePane");

        b_logout.setText("Logout");
        b_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logoutActionPerformed(evt);
            }
        });

        b_search.setText("Search");
        b_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_searchActionPerformed(evt);
            }
        });

        b_history.setText("History");
        b_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_historyActionPerformed(evt);
            }
        });

        tp_acc_det.setEditable(false);
        tp_acc_det.setBorder(null);
        tp_acc_det.setFont(new java.awt.Font("Quartz MS", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(tp_acc_det);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/user.jpg"))); // NOI18N

        javax.swing.GroupLayout p_sidePaneLayout = new javax.swing.GroupLayout(p_sidePane);
        p_sidePane.setLayout(p_sidePaneLayout);
        p_sidePaneLayout.setHorizontalGroup(
            p_sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sidePaneLayout.createSequentialGroup()
                .addGroup(p_sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_sidePaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(p_sidePaneLayout.createSequentialGroup()
                        .addGroup(p_sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_sidePaneLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(p_sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b_history, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(b_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(p_sidePaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_sidePaneLayout.setVerticalGroup(
            p_sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_sidePaneLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_history, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        p_sview.add(p_sidePane, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_sview, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_mview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p_mview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_sview, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean properInput(String _uid,char[] pwd){
        if(_uid.length()>1 && String.valueOf(pwd).length()>0 ) {
            if(_uid.charAt(0)=='L'||_uid.charAt(0)=='l'||
                    _uid.charAt(0)=='j'||_uid.charAt(0)=='J'||
                        _uid.charAt(0)=='r'||_uid.charAt(0)=='R'){
                String _sid = _uid.substring(1);
                for(int i=1;i<_uid.length();i++) {
                    if(!(_uid.charAt(i)>='0' && _uid.charAt(i)<='9')) return false ;
                }
                return true;
            }
        }
        return false;
    }
    
    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // TODO add your handling code here:
        String _uid = getUserID() ;
        char[] _pwd = getUserPW() ;
        if(!properInput(_uid,_pwd)) {
            l_login_result.setText("<html><font color = red>Invalid Input Entries</font></html>");
            rapplet.reset();
            return ;
        }
        int _id ;
        boolean ok = true;
        if(_uid.charAt(0)=='R'||_uid.charAt(0)=='r'){
            if(_uid.length()==2 && _uid.charAt(1)=='0') { 
                _registrar = new Registrar();
                if(_registrar.getName() == null) { ok = false; }
                else if(_registrar.validateLogin(_pwd)) {
                    l_login_result.setText("Login Successfull");

                    tp_acc_det.setText("User Name : "+_registrar.getName()+"\n"+
                                        "User ID : R"+Integer.toString(_registrar.getID()));

                   _cut = User.REGISTRAR ;
                   rapplet.reset();
                   
                   rapplet._sideview.show(rapplet._sv_p, Main.S_USER);
                   rapplet._mainview.show(rapplet._mv_p, Main.M_REGVIEW);
                } else 
                    ok = false;
            } else
                ok = false;
            
        }else if(_uid.charAt(0)=='L'||_uid.charAt(0)=='l'){
            _id = Integer.parseInt(_uid.substring(1));
            _lawyer = new Lawyer(_id);
            if (_lawyer.getName() == null) {
                ok = false;
            } else if(_lawyer.validateLogin(_pwd)) {
                l_login_result.setText("Login Successfull");
                
                tp_acc_det.setText("User Name : "+_lawyer.getName()+"\n"+
                                    "User ID : L"+Integer.toString(_lawyer.getID()));
                
               _cut = User.LAWYER ;
               rapplet.reset();
               
                rapplet._sideview.show(rapplet._sv_p, Main.S_USER);
                rapplet._mainview.show(rapplet._mv_p, Main.M_BLANK);
                b_history.setEnabled(true);
            }else
                ok = false;
        } else if(_uid.charAt(0)=='J'||_uid.charAt(0)=='j'){
            _id = Integer.parseInt(_uid.substring(1));
            _judge = new Judge(_id);
            if (_judge.getName() == null) {
                ok = false;
            } else if(_judge.validateLogin(_pwd)) {
                l_login_result.setText("Login Successfull");
                
                tp_acc_det.setText("User Name : "+_judge.getName()+"\n"+
                                    "User ID : J"+Integer.toString(_judge.getID()));
                
               _cut = User.JUDGE ;
                rapplet.reset();
                
                rapplet._sideview.show(rapplet._sv_p, Main.S_USER);
                rapplet._mainview.show(rapplet._mv_p, Main.M_BLANK);
            }else
                ok = false;
        }
        if(!ok) {
            l_login_result.setText("<html><font color = red>Log in Unsuccessful !</font></html>");
        }
        rapplet.reset();
    }//GEN-LAST:event_b_loginActionPerformed

    private void b_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logoutActionPerformed
        // TODO add your handling code here:
        
        if(_cut==User.JUDGE) _judge = null ;
        else if(_cut==User.LAWYER) _lawyer = null ;
        else if(_cut==User.REGISTRAR) _registrar = null ;
        
        b_history.setEnabled(false);
        i_loginid.setText("");
        i_pswd.setText("");
        l_login_result.setText("Successfully Logged Out");
        rapplet.reset();
        
        rapplet._sideview.show(rapplet._sv_p, Main.S_LOGIN);
        rapplet._mainview.show(rapplet._mv_p, Main.M_BLANK);
    }//GEN-LAST:event_b_logoutActionPerformed

    private void b_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_searchActionPerformed
        // TODO add your handling code here:
        rapplet._searchpanel.initialize("Search Old Cases");
        rapplet.reset();
        rapplet._mainview.show(rapplet._mv_p, Main.M_SEARCH);
    }//GEN-LAST:event_b_searchActionPerformed

    private void b_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_historyActionPerformed
        // TODO add your handling code here:
        Case _ref = null;
        if(_cut==User.LAWYER){
            try {
                Lawyer _lw = (Lawyer) getCU();
                if(_lw.getLOCSize()>0){   
                    int[] _iloc = _lw.getListOfCases();
                    ArrayList<Case> _loc = new ArrayList<>();
                    for(int _tmp : _iloc){
                        _ref = new Case(_tmp);
                        _loc.add(_ref);
                    }
                    rapplet._tableview.populateTable(_loc);
                }
                rapplet._tableview.setHeading("History of Visited Cases");
                rapplet.reset();
                rapplet._mainview.show(rapplet._mv_p,Main.M_TABVIEW);
            } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.err.println("History enabled for non-Lawyer users");
        }
    }//GEN-LAST:event_b_historyActionPerformed

    private void i_pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_pswdActionPerformed
        // TODO add your handling code here:
        b_loginActionPerformed(evt);
    }//GEN-LAST:event_i_pswdActionPerformed
    
    
    public void setRA(Main _ra){
        rapplet = _ra ;
        
        p_mview.add(_ra._caseinfo,Main.M_CASEINFO);
        p_mview.add(_ra._regview,Main.M_REGVIEW);
        p_mview.add(_ra._searchpanel,Main.M_SEARCH);
        p_mview.add(_ra._tableview,Main.M_TABVIEW);
        p_mview.add(_ra._updatehearing,Main.M_UPDATEH);
        p_mview.add(_ra._newcase,Main.M_NEWCASE);
        p_mview.add(_ra._slotview,Main.M_SLOTVIEW);
        
        _ra._mainview = (CardLayout) p_mview.getLayout();
        _ra._sideview = (CardLayout) p_sview.getLayout();
        
        _ra._sv_p = p_sview ;
        _ra._mv_p = p_mview ;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_history;
    private javax.swing.JButton b_login;
    private javax.swing.JButton b_logout;
    private javax.swing.JButton b_search;
    private javax.swing.JTextField i_loginid;
    private javax.swing.JPasswordField i_pswd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_login_result;
    private javax.swing.JPanel p_blank;
    private javax.swing.JPanel p_loginPane;
    public javax.swing.JPanel p_mview;
    private javax.swing.JPanel p_sidePane;
    public javax.swing.JPanel p_sview;
    private javax.swing.JTextPane tp_acc_det;
    // End of variables declaration//GEN-END:variables

    public String getUserID(){
        return i_loginid.getText() ;
    }
    
    public char[] getUserPW(){
        return i_pswd.getPassword() ;
    }
    
}
