/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Panels;

import JISS.Case;
import JISS.Case.Crime;
import JISS.Main;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandesh
 */
public class NewCase extends javax.swing.JPanel {

    /**
     * Creates new form NewCase
     */
    public NewCase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_heading = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        l_ct = new javax.swing.JTextField();
        l_dn = new javax.swing.JTextField();
        l_da = new javax.swing.JTextField();
        l_ln = new javax.swing.JTextField();
        l_ppn = new javax.swing.JTextField();
        l_jn = new javax.swing.JTextField();
        l_naf = new javax.swing.JTextField();
        l_loc = new javax.swing.JTextField();
        l_coc = new javax.swing.JTextField();
        l_doa = new javax.swing.JTextField();
        b_done = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        b_close = new javax.swing.JButton();

        l_heading.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        l_heading.setForeground(new java.awt.Color(51, 153, 255));
        l_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_heading.setText("New Case Entry");

        jLabel2.setText("Crime Type ");

        jLabel3.setText("Defendant's Name");

        jLabel4.setText("Defendant's Address");

        jLabel5.setText("Lawyer's Name");

        jLabel6.setText("Public Prosecutor's Name");

        jLabel7.setText("Judge's Name");

        jLabel8.setText("Name of Arresting Officer");

        jLabel9.setText("Location Of Crime");

        jLabel10.setText("Date of Crime Commission");

        jLabel11.setText("Date of Arrest");

        b_done.setText("Next");
        b_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_doneActionPerformed(evt);
            }
        });

        jLabel12.setText("Date Format : yyyy-[m]m-[d]d");

        b_close.setText("x");
        b_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_close))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_loc, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_naf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_jn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_ppn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_ln))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_da))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_ct)
                                    .addComponent(l_dn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_coc)
                                    .addComponent(l_doa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 74, Short.MAX_VALUE)
                                .addComponent(b_done, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_ct, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_dn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_da, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_ln, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_ppn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_jn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_naf, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_loc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_coc, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_doa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(b_done, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_closeActionPerformed
        // TODO add your handling code here:
        rapplet.reset();
        rapplet._mainview.show(rapplet._mv_p,Main.M_REGVIEW);
    }//GEN-LAST:event_b_closeActionPerformed

    private void b_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_doneActionPerformed
        // TODO add your handling code here:
        if(!setVariables()) {
            JOptionPane.showMessageDialog(rapplet._mv_p, "Invalid Input Format");
            return;
        }
        if(_mode==M_NC){
            rapplet._slotview.upSlots();
            rapplet._slotview.setPrev(Main.M_NEWCASE);
            rapplet._slotview.setMode(SlotView.M_NC);
            rapplet.reset();
            rapplet._mainview.show(rapplet._mv_p, Main.M_SLOTVIEW);
        }else{
            _tcase = new Case(_cref);

            _tcase.getCrime().setDoA(_doa_i);
            _tcase.getCrime().setCoC(_coc_i);
            _tcase.getCrime().setNoO(_naf_i);
            _tcase.getCrime().setCT(_ct_i);
            _tcase.getCrime().setLoC(_loc_i);
            _tcase.setDoS(_cref.getDoS());
            _tcase.setDN(_dn_i);
            _tcase.setDA(_da_i);
            _tcase.setLN(_ln_i);
            _tcase.setPPN(_ppn_i);
            _tcase.setJN(_jn_i);
            
            _cref.updateCD(_tcase);
            JOptionPane.showMessageDialog(rapplet._mv_p, "Case-Details Succesfully Edited");
            rapplet.reset();
            rapplet._mainview.show(rapplet._mv_p, Main.M_REGVIEW);
        }
    }//GEN-LAST:event_b_doneActionPerformed
    
    private Main rapplet;

    public void setRA(Main _ra) {
        rapplet = _ra;
    }
    
    Date _doa_i;
    Date _coc_i;
    String _naf_i;
    String _ct_i;
    String _loc_i;
    
    String _dn_i;
    String _da_i;
    String _ln_i;
    String _ppn_i;
    String _jn_i;
    
    Date _dos_i;
    
    public final static int M_NC = 1;
    public final static int M_UC = 2;
    
    public Case createCase(Date _dos_n){
        _dos_i = _dos_n ;
        Case _cref = new Case(_doa_i, _coc_i, _naf_i, _ct_i, _loc_i, _dos_i, _dn_i, _da_i, _ln_i, _ppn_i, _jn_i);
        return _cref;
    }
    
    public boolean checkForString(String str){
        for(int i=0;i<str.length();i++)
        {
            if(!((str.charAt(i)>='a' && str.charAt(i)<='z')||
                    (str.charAt(i)>='A' && str.charAt(i)<='Z')||
                        str.charAt(i)==' ')) return false ;
        }
        return true;
    }
    
    public boolean setVariables(){
        _ct_i = l_ct.getText();
        _da_i = l_da.getText();
        _loc_i = l_loc.getText();
        
        if (checkForString(l_dn.getText())) {
            _dn_i = l_dn.getText();
        } else {
            return false;
        }
        if (checkForString(l_jn.getText())) {
            _jn_i = l_jn.getText();
        } else {
            return false;
        }
        if (checkForString(l_ln.getText())) {
            _ln_i = l_ln.getText();
        } else {
            return false;
        }
        if (checkForString(l_ppn.getText())) {
            _ppn_i = l_ppn.getText();
        } else {
            return false;
        }
        if (checkForString(l_naf.getText())) {
            _naf_i = l_naf.getText();
        } else {
            return false;
        }
        
        try{
            _coc_i = Date.valueOf(l_coc.getText());
            _doa_i = Date.valueOf(l_doa.getText());
        }catch(Exception ex){
            return false;
        }
        
        return true;
    }
    
    public void clearAll(){
        l_coc.setText("");
        l_ct.setText("");
        l_da.setText("");
        l_dn.setText("");
        l_doa.setText("");
        l_jn.setText("");
        l_ln.setText("");
        l_loc.setText("");
        l_naf.setText("");
        l_ppn.setText("");
        
        _doa_i = null ;
        _coc_i = null ;
        _naf_i = null ;
        _ct_i = null ;
        _loc_i = null ;
        _dn_i = null ;
        _da_i = null ;
        _ln_i = null ;
        _ppn_i = null ;
        _jn_i = null ;
        _dos_i = null ;
    }
    
    public void setHeading(String _str){
        l_heading.setText(_str);
    }
    
    private int _mode ;
    
    public void setMode(int _m){
        _mode = _m ;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_close;
    private javax.swing.JButton b_done;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField l_coc;
    private javax.swing.JTextField l_ct;
    private javax.swing.JTextField l_da;
    private javax.swing.JTextField l_dn;
    private javax.swing.JTextField l_doa;
    private javax.swing.JLabel l_heading;
    private javax.swing.JTextField l_jn;
    private javax.swing.JTextField l_ln;
    private javax.swing.JTextField l_loc;
    private javax.swing.JTextField l_naf;
    private javax.swing.JTextField l_ppn;
    // End of variables declaration//GEN-END:variables
    
    Case _cref ;
    Case _tcase ;
    
    public void populateInfo(Case _ref){
        _cref = _ref;
        Crime _crime = _ref.getCrime();
        l_ct.setText(_crime.getCT());
        l_coc.setText(_crime.getCoC().toString());
        l_doa.setText(_crime.getDoA().toString());
        l_loc.setText(_crime.getLoC());
        l_naf.setText(_crime.getNoO());
        
        l_da.setText(_ref.getDA());
        l_dn.setText(_ref.getDN());
        l_ln.setText(_ref.getLN());
        l_jn.setText(_ref.getJN());
        l_ppn.setText(_ref.getPPN());
    }

}
